# fly.toml app configuration file generated for tailscale-pgproxy-fixie on 2024-04-12T11:13:20+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tailscale-pgproxy-fixie'
primary_region = 'cdg'

[build]

[[services]]
  protocol = "udp"
  internal_port = 41641
  processes = ["app"]

  [[services.ports]]
    port = 41641
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75

[[vm]]
  size = 'shared-cpu-1x'
